name: Github Actions Demo
on: push
jobs:
  Example-Actions-Job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The Job was triggered by ${{github.event_name}} event"

      - run: echo "This job is running on ${{runner.os}} os provided by Github"

      - run: echo "The name of branch is ${{github.ref}}" and repository is ${{github.repository}}

      - name: Checkout repository code
        uses: actions/checkout@v4.1.0

      - run: echo "the ${{github.repo}} has been cloned to the runner"

      - run: echo "repo has been copied to ${{github.workspace}}"

      - run: echo "The workflow is now ready for test"

      - name: conditional step
        if: ${{github.event_name == 'pull_request'}}
        run: echo "this is a pull request"

      - name: list directory of code repo
        run: |
          ls ${{github.workspace}}

      - name: setup dotnet on runner 
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.x
          
      - name: Display dotnet version 
        run: dotnet --version

      - name: preinstall tool
        run: $echo "pre install tools are located at ${{runner.tool_cache}}"

      - name: list preinstall tool 
        run: |
          ls ${{runner.tool_cache}} 

      - run: echo "job status is ${{job.status}}"

      


        
